//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zachet
{
    using System;
    using System.Collections.Generic;

    public partial class Routes
    {
        public int Id { get; set; }
        public int VehicleId { get; set; }
        public int? DriverId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string StartLocation { get; set; }
        public string EndLocation { get; set; }
        public int Distance { get; set; }
        public Nullable<int> UserId { get; set; }
        public string VehicleStatus { get; set; }
        
        public virtual Drivers Drivers { get; set; }
        public virtual Vehicles Vehicles { get; set; }
        public virtual Users Users { get; set; }
    }
}
