//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zachet
{
    using System;
    using System.Collections.Generic;

    public partial class Vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicles()
        {
            this.Routes = new HashSet<Routes>();
        }

        public int Id { get; set; }
        public string LicensePlate { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public int YearOfManufacture { get; set; }
        public int Mileage { get; set; }
        public string Status { get; set; }
        public int MaintenanceMileage { get; set; } = 10000;
        public DateTime? LastMaintenanceDate { get; set; }

        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Routes> Routes { get; set; }

        public bool NeedsMaintenance()
        {
            return Mileage >= MaintenanceMileage;
        }

        public void PerformMaintenance()
        {
            LastMaintenanceDate = DateTime.Now;
            Status = "Обслужено"; 
                                 
        }

        public override string ToString()
        {
            return $"{Manufacturer} {Model}";
        }
        

    }

}
